default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['USERNAME'] %> # same name for a superuser
      password: <%= ENV['PASSWORD'] %> # same password for the database owner. 
      host: <%= ENV['IP'] %> # config the hba_file and fix the template 1.
development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test


production:
  <<: *default
  database: app_production
  
  
# The directory is part of gitignore